on: [push, pull_request]
name: Android
jobs:
  Integration:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            .buildozer
          key: ${{ hashFiles('tools/build/buildozer.spec') }}

      - name: Setup environment
        run: |
          pip install buildozer
          pip install Cython
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt -y install libltdl-dev automake
      - name: buildozer android debug
        run: |
          sh tools/build/build-android.sh
      - uses: actions/upload-artifact@v4.6.1
        with:
          path: .buildozer/bin/*.apk
